from omegaconf import OmegaConf

config = {
  'general': {
    'experiment_name': 'pipeline rework',
    'seed': 31415,
    'num_classes': 2,
  },
  'paths': {
    'path_to_train_data': './data/train.csv',
    'path_to_test_data': './data/test.csv',
    'path_to_checkpoints': './checkpoints',
    'path_to_logs': './logs/${general.experiment_name}.txt',
    'path_to_submission': './submission.csv',
    'path_to_results': './result.md',
  },
  'data': {
    'target_col': 'Survived',
    'id_col': 'PassengerId',
  },
  'cv': {
    'n_splits': 5,
    'shuffle': True,
    'random_state': '${general.seed}',
  },
  'fit': {
    'val_size': 0.2,
  },
  'models_params': {
    'regression': {
      'C': 0.1,
      'class_weight': None,
      'l1_ratio': 0.5,
      'max_iter': 2000,
      'solver': 'saga',
    },
    'ridge': {
      'alpha': 1.0,
      'class_weight': None,
      'max_iter': 2000,
      'solver': 'auto',
    },
    'lasso': {
      'C': 0.1,
      'class_weight': None,
      'max_iter': 2000,
      'penalty': 'l1',
      'solver': 'liblinear',
    },
    'elasticnet': {
      'C': 0.1,
      'class_weight': None,
      'l1_ratio': 0.5,
      'max_iter': 2000,
      'penalty': 'elasticnet',
      'solver': 'saga',
    },
    'KNN': {
      'n_neighbors': 11,
      'weights': 'uniform',
      'leaf_size': 50,
      'p': 1,
    },
    'decision_tree': {
      'ccp_alpha': 0.001,
      'class_weight': None,
      'criterion': 'log_loss',
      'max_depth': 10,
      'max_features': None,
      'min_samples_leaf': 5,
      'min_samples_split': 20,
      'splitter': 'random',
    },
    'random_forest': {
      'bootstrap': True,
      'class_weight': 'balanced',
      'criterion': 'gini',
      'max_depth': None,
      'max_features': 'sqrt',
      'min_samples_leaf': 2,
      'min_samples_split': 10,
      'n_estimators': 200,
    },
    'catboost': {
      'iterations': 500,
      'depth': 6,
      'learning_rate': 0.01,
      'l2_leaf_reg': 10,
      'random_strength': 5,
      'bagging_temperature': 2,
      'border_count': 64,
      'min_data_in_leaf': 10,
      'subsample': 0.6,
      'colsample_bylevel': 0.9,
      'verbose': False,
      'allow_writing_files': False,
    },
    'lightgbm': {
      'n_estimators': 800,
      'learning_rate': 0.01,
      'num_leaves': 127,
      'max_depth': 8,
      'min_child_samples': 10,
      'subsample': 0.6,
      'colsample_bytree': 1.0,
      'reg_alpha': 0.1,
      'reg_lambda': 5,
      'class_weight': 'balanced',
      'n_jobs': 1,
      'force_col_wise': True,
      'verbose': -1,
    },
    'xgboost': {
      'n_estimators': 500,
      'learning_rate': 0.01,
      'max_depth': 8,
      'min_child_weight': 1,
      'subsample': 0.7,
      'colsample_bytree': 0.7,
      'reg_alpha': 1,
      'reg_lambda': 5,
      'gamma': 0.1,
      'scale_pos_weight': 1,
      'n_jobs': 1,
    },
    'voting': {
      'voting': 'soft',
      'models': {
        'regression': 0,
        'ridge': 0,
        'lasso': 0,
        'elasticnet': 0,
        'KNN': 1,
        'decision_tree': 0,
        'random_forest': 1,
        'catboost': 2,
        'lightgbm': 1,
        'xgboost': 1,
      },
    },
    'stacking': {
      'models': {
        'regression': 0,
        'ridge': 0,
        'lasso': 0,
        'elasticnet': 0,
        'KNN': 1,
        'decision_tree': 0,
        'random_forest': 1,
        'catboost': 2,
        'lightgbm': 1,
        'xgboost': 1,
      },
    },
    'DNN': {
      'hidden_dims': [256, 128],
      'dropout': 0.3,
      'lr': 0.001,
      'batch_size': 64,
      'num_epochs': 100,
      'patience': 30,
      'weight_decay': 0.05,
      'device': 'auto',
      'batch_norm': True,
    },
  },
  'models_to_evaluate': [
    'regression',
    'ridge',
    'lasso',
    'elasticnet',
    'KNN',
    'decision_tree',
    'random_forest',
    'catboost',
    'lightgbm',
    'xgboost',
    'voting',
    'stacking',
    'DNN',
  ],
  'training_model': 'voting',
  'need_scaler': True,
  'mode': 'fit',
  'rerun': True,
  'logging': True,
  'save_best_model': True,
  'save_last_model': True,
  'model_type': 'classification',
  'metric': 'accuracy',
  'is_negative_metric': False,
}

config = OmegaConf.create(config)
