from omegaconf import OmegaConf

config = {
  'general': {
    'experiment_name': 'simple_models_with_scaler',
    'seed': 31415,
    'num_classes': 2,
  },
  'paths': {
    'path_to_train_data': './data/train.csv',
    'path_to_test_data': './data/test.csv',
    'path_to_checkpoints': './checkpoints',
    'path_to_logs': './logs/${general.experiment_name}',
    'path_to_submission': './submission.csv',
  },
  'data': {
    'target_col': 'Survived',
    'id_col': 'PassengerId',
  },
  'cv': {
    'n_splits': 5,
    'shuffle': True,
    'random_state': '${general.seed}',
  }, 
  'models_params': {
    'log_reg': {
      'C': 0.1,
      'class_weight': None,
      'l1_ratio': 0.5,
      'max_iter': 2000,
      'solver': 'saga',
    },
    'KNN': {
       'n_neighbors': 21,
       'weights': 'uniform',
       'leaf_size': 20,
       'p': 1,
    },
    'decision_tree': {
      'ccp_alpha': 0.001,
      'class_weight': None,
      'criterion': 'log_loss',
      'max_depth': 10,
      'max_features': None,
      'min_samples_leaf': 5,
      'min_samples_split': 20,
      'splitter': 'random',
    },
    'random_forest': {
      'bootstrap': True,
      'class_weight': 'balanced',
      'criterion': 'gini',
      'max_depth': None,
      'max_features': 'sqrt',
      'min_samples_leaf': 10,
      'min_samples_split': 10,
      'n_estimators': 200,
    },
    'catboost': {
      'iterations': 300,
      'depth': 8,
      'learning_rate': 0.03,
      'l2_leaf_reg': 5,
      'random_strength': 10,
      'bagging_temperature': 0,
      'border_count': 32,
      'min_data_in_leaf': 10,
      'subsample': 0.8,
      'colsample_bylevel': 0.9,
      'verbose': False,
      'allow_writing_files': False,
    },
    'lightgbm': {
      'n_estimators': 800,
      'learning_rate': 0.01,
      'num_leaves': 127,
      'max_depth': 8,
      'min_child_samples': 10,
      'subsample': 0.6,
      'colsample_bytree': 1.0,
      'reg_alpha': 0.1,
      'reg_lambda': 5,
      'class_weight': 'balanced',
    },
    'xgboost': {
      'n_estimators': 800,
      'learning_rate': 0.05,
      'max_depth': 8,
      'min_child_weight': 3,
      'subsample': 1.0,
      'colsample_bytree': 0.8,
      'reg_alpha': 0,
      'reg_lambda': 1,
      'gamma': 0.1,
      'scale_pos_weight': 1.6,
    },
    'DNN': {
      'hidden_dims': [128, 64],
      'dropout': 0.3,
      'lr': 0.001,
      'batch_size': 32,
      'num_epochs': 100,
      'patience': 15,
      'weight_decay': 0.0001,
      'device': 'auto',
    },
  },
  'training_model': 'catboost',
  'need_scaler': True,
  'mode': 'submit', # train / fit / submit
  'logging': True,
  'rerun': False,
  'save_best_model': True,
  'metric': 'accuracy',
}

config = OmegaConf.create(config)
